### ISSUE TITLE
Issue "Contacto"

### ISSUE THREAD

**Issue by alexandralozano** [tozanni/covid_rcp_webapp#4]
En el apartado de "Contacto" cuando se selecciona "Enviar", se redirige a la página de probabilidad RcP.

**Comment by Darival** [comment]
Este formulario no tiene aun un endpint en el backend. de momento es una vista solamente.

**Comment by quiquegarcia** [comment]
@tozanni tienes el dato de a qué correo deben llegar las notificaciones cuando llenan este formulario?

**Comment by Darival** [comment]
ya se implemento la funcionalidad del formulario de contacto desde 3e4b16ec3f8cea92635eb7193f98d814641be92a
