### ISSUE TITLE
Aviso de privacidad

### ISSUE THREAD

**Issue by quiquegarcia** [tozanni/covid_rcp_webapp#8]
Actualizar el aviso de privacidad

@tozanni dónde podemos adquirir la versión actualizada?

**Comment by rbtote** [comment]
@quiquegarcia 
En qué parte de la aplicación de añade el aviso? La pestaña de descripción del proyecto o una nueva.
Tenemos ya un archivo con los avisos y leyendas de privacidad proporcionado por Etna

**Comment by Darival** [comment]
@rbtote deberia ir en la descripcion y en las pantallas de inicio de sesion

**Comment by quiquegarcia** [comment]
@rbtote Primero debes crear un archivo dentro de la carpeta Views, puedes basarte en ```About.vue```, acto seguido necesitas registrar una ruta dentro del archivo ```common/routes.js```

Con esa ruta creada hay que editar los archivos de vistas que menciona @Darival para incluir ese link usando los helpers de router
